include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: true
  exclude:
    - build/**
    - gql/**
    - '**/*.g.dart'
    - '**/*.freezed.dart'


linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - no_logic_in_create_state
    - avoid_positional_boolean_parameters
    - avoid_void_async
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - parameter_assignments
    - prefer_constructors_over_static_methods
    - prefer_null_aware_method_calls
    - unnecessary_await_in_return
    - unnecessary_to_list_in_spreads
    - use_colored_box
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
