name: git_explorer
description: Simple app which use GitHub API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: 8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  dio: 5.3.2
  pretty_dio_logger: 1.3.1
  injectable: 2.3.0
  injectable_generator: 2.4.0
  json_annotation: 4.8.1
  equatable: ^2.0.0
  rxdart: ^0.27.7
  go_router: ^10.1.0
  freezed: ^2.4.1


dev_dependencies:
  bloc_test: 9.1.4
  flutter_test:
    sdk: flutter
  mocktail: 1.0.0
  mockito: ^5.4.2
  build_runner: 2.4.6
  json_serializable: 6.7.1
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  generate: true
